#!/usr/bin/env bash
# ============================================================================
# Generate infra/.env for the test-server deploy: random, consistent secrets
# wired to the compose service names. Run once, tweak the PUBLIC_* / CORS lines
# for your host, then `docker compose -f docker-compose.deploy.yml up -d --build`.
# Requires: openssl.
# ============================================================================
set -euo pipefail
cd "$(dirname "$0")"

if [ -e .env ]; then
  echo "infra/.env already exists — refusing to overwrite. Remove it first to regenerate." >&2
  exit 1
fi

# A URL-safe secret (no /+= so it's fine in env values and connection strings).
rand() { openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32; }

PG_PW="$(rand)"
MINIO_PW="$(rand)"
TOTP_KEY="$(rand)"
LK_KEY="acdk_$(rand | head -c 12)"
LK_SECRET="$(openssl rand -hex 32)"
# Ed25519 PKCS#8 as single-line base64 of the DER: the backend strips PEM armor and
# base64-decodes, so a bare base64 body (env-friendly, no newlines) loads fine.
JWT_B64="$(openssl genpkey -algorithm ed25519 -outform DER 2>/dev/null | base64 | tr -d '\n')"

cat > .env <<EOF
# Generated by gen-deploy-env.sh — random, consistent secrets. DO NOT COMMIT.
# Before exposing externally, set the three PUBLIC/CORS lines to your host/domain.

# ---- infra credentials (used by docker-compose.deploy.yml) ------------------
POSTGRES_USER=accord
POSTGRES_PASSWORD=${PG_PW}
POSTGRES_DB=accord
MINIO_ROOT_USER=accord
MINIO_ROOT_PASSWORD=${MINIO_PW}
STORAGE_BUCKET=accord-attachments
STORAGE_AVATARS_BUCKET=accord-avatars

# ---- backend config (env_file) ----------------------------------------------
SERVER__HOST=0.0.0.0
SERVER__PORT=8090
SERVER__PRODUCTION=true
# EDIT: the externally-reachable URL of THIS backend (used in verification e-mails).
SERVER__PUBLIC_URL=http://localhost:8090
# EDIT: comma-separated client origins allowed by CORS. The desktop app's webview
# origin differs per OS: tauri://localhost on macOS/Linux, http(s)://tauri.localhost
# on Windows (WebView2) — all three are listed so the built app works everywhere.
# http://localhost:1420 covers a local dev client.
SERVER__CORS_ALLOWED_ORIGINS=tauri://localhost,http://tauri.localhost,https://tauri.localhost,http://localhost:1420

DATABASE__URL=postgres://accord:${PG_PW}@postgres:5432/accord
REDIS__URL=redis://redis:6379
NATS__URL=nats://nats:4222

# S3: ENDPOINT is what the backend signs against (internal); PUBLIC_ENDPOINT is what
# clients fetch avatars/attachments from — EDIT it to a host clients can reach.
STORAGE__ENDPOINT=http://minio:9000
STORAGE__PUBLIC_ENDPOINT=http://localhost:9000
STORAGE__REGION=us-east-1
STORAGE__BUCKET=accord-attachments
STORAGE__AVATARS_BUCKET=accord-avatars
STORAGE__ACCESS_KEY=accord
STORAGE__SECRET_KEY=${MINIO_PW}

# LiveKit (calls). URL is client-facing; key/secret MUST match livekit's LIVEKIT_KEYS.
LIVEKIT__URL=ws://localhost:7880
LIVEKIT__API_KEY=${LK_KEY}
LIVEKIT__API_SECRET=${LK_SECRET}

# 2FA TOTP secret-sealing key (AEAD).
AUTH__TOTP_ENC_KEY=${TOTP_KEY}

# EDIT: comma-separated emails promoted to instance admin at boot or the moment
# they register (the first administrator; more via the in-app admin panel).
# AUTH__BOOTSTRAP_ADMIN_EMAILS=you@example.com

# JWT signing key — single-line base64 of an Ed25519 PKCS#8 key.
JWT__PRIVATE_KEY_PEM=${JWT_B64}

# Transactional e-mail → Mailpit (test sink; read it at http://localhost:8025).
# For real delivery, point this at your SMTP provider, e.g. smtps://user:pass@smtp.host:465
EMAIL__SMTP_URL=smtp://mailpit:1025
EMAIL__FROM=Accord <no-reply@accord.local>
EOF

chmod 600 .env
echo "Wrote infra/.env with fresh secrets."
echo "Next: review SERVER__PUBLIC_URL / STORAGE__PUBLIC_ENDPOINT / SERVER__CORS_ALLOWED_ORIGINS, then:"
echo "  docker compose -f docker-compose.deploy.yml up -d --build"
